camera_count = 17
creation_date = 2024-12-13T15:19:05.947633
fps_sync_stream_processing = 100
save_tracked_points_video = true

[charuco]
columns = 4
rows = 5
board_height = 14.0
board_width = 10.0
dictionary = "DICT_4X4_50"
units = "cm"
aruco_scale = 0.75
square_size_overide_cm = 5.4
inverted = false
legacy_pattern = false
